//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VipMobileDBEntities : DbContext
    {
        public VipMobileDBEntities()
            : base("name=VipMobileDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Ponuda> Ponudas { get; set; }
        public virtual DbSet<Proizvodjac> Proizvodjacs { get; set; }
        public virtual DbSet<StavkaPonude> StavkaPonudes { get; set; }
        public virtual DbSet<TarifniPaket> TarifniPakets { get; set; }
        public virtual DbSet<Uredjaj> Uredjajs { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
    }
}
