//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uredjaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uredjaj()
        {
            this.StavkaPonudes = new HashSet<StavkaPonude>();
        }
    
        public int IDUredjaja { get; set; }
        public string Naziv { get; set; }
        public string Cena { get; set; }
        public string Model { get; set; }
        public string Boja { get; set; }
        public Nullable<int> IDProizvodjaca { get; set; }
    
        public virtual Proizvodjac Proizvodjac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPonude> StavkaPonudes { get; set; }
    }
}
